### ISSUE TITLE
Portable mode

### ISSUE THREAD

**Issue by AtmanActive** [ssebs/go-mmp#4]
Hi,

Thanks for this project, it looks really interesting.

However, the hardcoded config file path makes it unusable in portable mode (where an app is independent of the Installation path or a particular windows installation).

Advantages of running windows software in portable mode are numerous: never lose your config and time invested in setting up the software, and, also, have many versions set up in parallel (just by using different folder names), for testing, or for multiple use cases or multiple machines.

Here is how to make your app work in portable mode, in addition to the existing windows-way mode:
- on app startup, first discover your own executed path, then, check for the existence of a config file in the same folder on that path. If it exists, use that config file. If not, continue as normal.

In this way, advanced users can copy or create an empty config file in the same folder where the exe is and take it from there, having all data encapsulated in that one folder, without creating anything on well known windows paths (like C:\Users\xxx). Then, if needed, advanced users can easily copy the whole folder for backups, copy the whole folder to other machines, or, make copies to maintain several versions in parallel.

For non-advanced users, the app continues to work as described in your ReadMe (using C:\Users\xxx).

Thanks!

**Comment by ssebs** [comment]
@AtmanActive that's a great idea, thanks for the suggestion! I'll find some time and get to work.
